import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0a0a0f',
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 20,
  },
  permissionContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
    backgroundColor: '#0a0a0f',
  },
  permissionTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    marginTop: 20,
    marginBottom: 10,
    textAlign: 'center',
    color: '#00ffff',
    letterSpacing: 2,
  },
  permissionText: {
    fontSize: 16,
    textAlign: 'center',
    marginBottom: 30,
    color: '#8a8a9a',
    lineHeight: 24,
  },
  header: {
    backgroundColor: '#0d0d15',
    padding: 25,
    alignItems: 'center',
    position: 'relative',
    overflow: 'hidden',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0, 255, 255, 0.15)',
  },
  headerGlow: {
    position: 'absolute',
    top: -80,
    left: '20%',
    right: '20%',
    height: 120,
    backgroundColor: 'rgba(255, 0, 102, 0.06)',
    borderRadius: 100,
    opacity: 1,
  },
  titleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    zIndex: 2,
  },
  shieldIcon: {
    width: 50,
    height: 50,
    borderRadius: 4,
    backgroundColor: 'rgba(0, 255, 255, 0.08)',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 15,
    borderWidth: 1,
    borderColor: 'rgba(0, 255, 255, 0.3)',
  },
  titleText: {
    flex: 1,
  },
  appTitle: {
    fontSize: 28,
    fontWeight: '900',
    color: '#00ffff',
    letterSpacing: 3,
    textTransform: 'uppercase',
  },
  appSubtitle: {
    fontSize: 10,
    color: '#ff0066',
    letterSpacing: 5,
    marginTop: 4,
    textTransform: 'uppercase',
    opacity: 0.8,
  },
  safetyScoreContainer: {
    alignItems: 'center',
    padding: 30,
    backgroundColor: '#0a0a0f',
  },
  safetyScoreCircle: {
    width: 120,
    height: 120,
    borderRadius: 60,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#00ffff',
    backgroundColor: 'rgba(0, 255, 255, 0.04)',
  },
  safetyScoreNumber: {
    fontSize: 36,
    fontWeight: '900',
    color: '#00ffff',
    letterSpacing: 2,
  },
  safetyScoreLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: '#e0e0e0',
    textAlign: 'center',
    letterSpacing: 2,
    textTransform: 'uppercase',
  },
  controlsContainer: {
    paddingHorizontal: 20,
    marginBottom: 20,
  },
  controlButton: {
    backgroundColor: '#12121a',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 15,
    borderRadius: 4,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: 'rgba(0, 255, 255, 0.15)',
  },
  controlButtonActive: {
    backgroundColor: 'rgba(255, 0, 102, 0.15)',
    borderColor: '#ff0066',
  },
  settingsButton: {
    backgroundColor: 'rgba(255, 0, 102, 0.1)',
    borderColor: '#ff0066',
  },
  controlButtonText: {
    color: '#e0e0e0',
    fontSize: 14,
    fontWeight: '700',
    marginLeft: 10,
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  primaryButton: {
    backgroundColor: 'rgba(0, 255, 255, 0.1)',
    padding: 15,
    borderRadius: 4,
    minWidth: 200,
    borderWidth: 1,
    borderColor: '#00ffff',
  },
  buttonText: {
    color: '#00ffff',
    fontSize: 14,
    fontWeight: '700',
    textAlign: 'center',
    letterSpacing: 2,
    textTransform: 'uppercase',
  },
  loadingContainer: {
    alignItems: 'center',
    padding: 20,
  },
  loadingText: {
    marginTop: 10,
    fontSize: 16,
    color: '#666',
  },
  infoCard: {
    backgroundColor: '#0f0f1a',
    margin: 20,
    marginTop: 0,
    padding: 15,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: 'rgba(0, 255, 255, 0.12)',
  },
  alertCard: {
    backgroundColor: 'rgba(255, 0, 102, 0.08)',
    borderColor: '#ff0066',
    borderWidth: 1,
  },
  cardTitle: {
    fontSize: 13,
    fontWeight: '700',
    marginBottom: 10,
    color: '#00ffff',
    letterSpacing: 2,
    textTransform: 'uppercase',
  },
  infoText: {
    fontSize: 13,
    color: '#8a8a9a',
    marginBottom: 5,
  },
  warningText: {
    color: '#ff0066',
    fontWeight: 'bold',
  },
  riskFactor: {
    fontSize: 13,
    color: '#ff0066',
    marginBottom: 5,
  },
  recommendation: {
    fontSize: 13,
    color: '#00ffcc',
    marginBottom: 5,
  },
  alertItem: {
    marginBottom: 10,
    padding: 10,
    backgroundColor: 'rgba(255, 0, 102, 0.1)',
    borderRadius: 4,
    borderLeftWidth: 2,
    borderLeftColor: '#ff0066',
  },
  alertType: {
    fontSize: 12,
    fontWeight: '700',
    color: '#ff0066',
    marginBottom: 5,
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  alertMessage: {
    fontSize: 13,
    color: '#e0e0e0',
    marginBottom: 5,
  },
  alertPriority: {
    fontSize: 11,
    color: '#8a8a9a',
  },
  // Electric Scooter Warning Styles
  scooterWarningCard: {
    backgroundColor: 'rgba(255, 0, 102, 0.15)',
    borderColor: '#ff0066',
    borderWidth: 2,
    borderStyle: 'solid',
  },
  scooterWarningTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#ff0066',
    textAlign: 'center',
    marginBottom: 10,
    letterSpacing: 2,
    textTransform: 'uppercase',
  },
  scooterWarningText: {
    fontSize: 14,
    color: '#e0e0e0',
    fontWeight: '600',
    textAlign: 'center',
    marginBottom: 8,
  },
  scooterWarningTip: {
    fontSize: 13,
    color: '#00ffff',
    fontWeight: '500',
    textAlign: 'center',
    marginBottom: 8,
  },
  scooterWarningAction: {
    fontSize: 13,
    color: '#ff0066',
    fontWeight: 'bold',
    textAlign: 'center',
    backgroundColor: 'rgba(255, 0, 102, 0.1)',
    padding: 8,
    borderRadius: 4,
    marginTop: 5,
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  // Alert Banner Styles
  alertBanner: {
    backgroundColor: 'rgba(255, 0, 102, 0.2)',
    padding: 15,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginHorizontal: 20,
    borderRadius: 4,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#ff0066',
  },
  alertBannerText: {
    color: '#ff0066',
    fontSize: 12,
    fontWeight: '700',
    flex: 1,
    textAlign: 'center',
    letterSpacing: 3,
    textTransform: 'uppercase',
  },
  deactivateButton: {
    backgroundColor: '#ff0066',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 2,
  },
  deactivateButtonText: {
    color: '#0a0a0f',
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  alertButton: {
    backgroundColor: 'rgba(255, 0, 102, 0.15)',
    borderColor: '#ff0066',
  },
  listeningButton: {
    backgroundColor: 'rgba(0, 255, 204, 0.1)',
    borderColor: '#00ffcc',
  },
  handsFreeButton: {
    backgroundColor: 'rgba(0, 255, 255, 0.1)',
    borderColor: '#00ffff',
  },
  manualTriggerButton: {
    backgroundColor: 'rgba(255, 0, 102, 0.1)',
    borderColor: '#ff0066',
  },
  infoButton: {
    backgroundColor: 'rgba(0, 255, 255, 0.08)',
    borderColor: 'rgba(0, 255, 255, 0.3)',
  },
  demoButton: {
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  cyclingButton: {
    backgroundColor: 'rgba(0, 255, 204, 0.1)',
    borderColor: '#00ffcc',
  },
  cyclingActiveButton: {
    backgroundColor: 'rgba(0, 255, 204, 0.15)',
    borderColor: '#00ffcc',
  },
  testAlertButton: {
    backgroundColor: 'rgba(255, 0, 102, 0.1)',
    borderColor: '#ff0066',
  },
  alertActiveButton: {
    backgroundColor: 'rgba(255, 0, 102, 0.2)',
    borderWidth: 2,
    borderColor: '#ff0066',
  },
  // Voice Info Demo Styles
  voiceInfoDemoSection: {
    backgroundColor: '#0f0f1a',
    borderRadius: 4,
    padding: 16,
    marginTop: 8,
    borderWidth: 1,
    borderColor: 'rgba(0, 255, 255, 0.12)',
  },
  voiceInfoDemoTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: '#00ffff',
    marginBottom: 8,
    textAlign: 'center',
    letterSpacing: 2,
    textTransform: 'uppercase',
  },
  voiceInfoDemoNote: {
    fontSize: 11,
    color: '#666',
    marginBottom: 12,
    textAlign: 'center',
    fontStyle: 'italic',
  },
  voiceInfoDemoButtons: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    flexWrap: 'wrap',
    gap: 8,
  },
  voiceInfoDemoButton: {
    backgroundColor: '#0f0f1a',
    borderRadius: 4,
    padding: 12,
    alignItems: 'center',
    minWidth: 80,
    borderWidth: 1,
    borderColor: 'rgba(0, 255, 255, 0.2)',
  },
  voiceInfoDemoButtonText: {
    color: '#00ffff',
    fontSize: 11,
    fontWeight: '600',
    marginTop: 4,
    textAlign: 'center',
    letterSpacing: 0.5,
  },
  voiceInfoResponseCard: {
    backgroundColor: 'rgba(0, 255, 255, 0.06)',
    borderRadius: 8,
    padding: 14,
    marginTop: 12,
    borderWidth: 1,
    borderColor: 'rgba(0, 255, 255, 0.2)',
  },
  voiceInfoResponseHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
    gap: 6,
  },
  voiceInfoResponseLabel: {
    color: '#00ffff',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 2,
  },
  voiceInfoResponseText: {
    color: '#c0c0d0',
    fontSize: 13,
    lineHeight: 20,
  },
  // Modal Styles
  modalContainer: {
    flex: 1,
    backgroundColor: '#0a0a0f',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    backgroundColor: '#0d0d15',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0, 255, 255, 0.15)',
  },
  modalTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#00ffff',
    letterSpacing: 2,
    textTransform: 'uppercase',
  },
  modalContent: {
    flex: 1,
    padding: 20,
  },
  modalDescription: {
    fontSize: 14,
    color: '#8a8a9a',
    lineHeight: 22,
    marginBottom: 30,
  },
  inputGroup: {
    marginBottom: 25,
  },
  inputLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: '#00ffff',
    marginBottom: 5,
    letterSpacing: 2,
    textTransform: 'uppercase',
  },
  inputHint: {
    fontSize: 13,
    color: '#666',
    marginBottom: 10,
    lineHeight: 20,
  },
  textInput: {
    borderWidth: 1,
    borderColor: 'rgba(0, 255, 255, 0.2)',
    borderRadius: 4,
    padding: 15,
    backgroundColor: '#0f0f1a',
    fontSize: 16,
    color: '#e0e0e0',
  },
  inputError: {
    borderColor: '#ff0066',
    backgroundColor: 'rgba(255, 0, 102, 0.05)',
  },
  // (Voice Trigger Status Styles moved to bottom of stylesheet)
  contactRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  contactInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: 'rgba(0, 255, 255, 0.2)',
    borderRadius: 4,
    padding: 15,
    backgroundColor: '#0f0f1a',
    fontSize: 16,
    color: '#e0e0e0',
    marginRight: 10,
  },
  addContactButton: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 15,
    borderWidth: 1,
    borderColor: 'rgba(0, 255, 255, 0.3)',
    borderRadius: 4,
    borderStyle: 'dashed',
    justifyContent: 'center',
  },
  addContactText: {
    color: '#00ffff',
    fontSize: 14,
    marginLeft: 5,
    letterSpacing: 1,
  },
  warningBox: {
    flexDirection: 'row',
    backgroundColor: 'rgba(255, 0, 102, 0.08)',
    padding: 15,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: 'rgba(255, 0, 102, 0.2)',
    alignItems: 'flex-start',
  },
  warningText: {
    flex: 1,
    fontSize: 13,
    color: '#8a8a9a',
    marginLeft: 10,
    lineHeight: 20,
  },
  modalFooter: {
    flexDirection: 'row',
    padding: 20,
    backgroundColor: '#0d0d15',
    borderTopWidth: 1,
    borderTopColor: 'rgba(0, 255, 255, 0.1)',
  },
  cancelButton: {
    flex: 1,
    padding: 15,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.15)',
    marginRight: 10,
  },
  cancelButtonText: {
    textAlign: 'center',
    fontSize: 14,
    color: '#8a8a9a',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  saveButton: {
    flex: 2,
    backgroundColor: 'rgba(255, 0, 102, 0.2)',
    padding: 15,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#ff0066',
  },
  saveButtonDisabled: {
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  saveButtonText: {
    textAlign: 'center',
    fontSize: 14,
    fontWeight: '700',
    color: '#ff0066',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  // Voice guidance styles
  labelWithVoice: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 5,
  },
  voiceHelpButton: {
    padding: 8,
    borderRadius: 4,
    backgroundColor: 'rgba(0, 255, 255, 0.08)',
    borderWidth: 1,
    borderColor: 'rgba(0, 255, 255, 0.3)',
    marginLeft: 10,
  },
  // Flashy Dynamic Styles
  safetyScoreWrapper: {
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
  },
  pulseRing: {
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
  },
  pulseRingInner: {
    width: 160,
    height: 160,
    borderRadius: 80,
    borderWidth: 1,
    opacity: 0.3,
  },
  scoreGlow: {
    position: 'absolute',
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: 'rgba(0, 255, 255, 0.05)',
    opacity: 0.5,
  },
  scoreGlowRing: {
    position: 'absolute',
    width: 140,
    height: 140,
    borderRadius: 70,
    borderWidth: 1,
    borderColor: '#00ffff',
    backgroundColor: 'transparent',
  },
  shieldOverlay: {
    position: 'absolute',
    bottom: 10,
    right: 10,
  },
  statusIndicators: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: '100%',
    marginTop: 20,
    paddingHorizontal: 20,
  },
  statusItem: {
    alignItems: 'center',
    opacity: 0.9,
  },
  statusText: {
    color: '#8a8a9a',
    fontSize: 9,
    fontWeight: '700',
    marginTop: 4,
    letterSpacing: 2,
    textTransform: 'uppercase',
  },
  // Enhanced Control Styles
  primaryActionButton: {
    backgroundColor: '#0f0f1a',
    borderRadius: 4,
    marginBottom: 20,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#00ffff',
  },
  primaryActionButtonActive: {
    borderColor: '#ff0066',
  },
  primaryActionButtonLoading: {
    borderColor: '#00ffff',
    opacity: 0.7,
  },
  buttonGradientOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 255, 255, 0.04)',
  },
  buttonContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
    zIndex: 2,
  },
  primaryButtonText: {
    color: '#00ffff',
    fontSize: 14,
    fontWeight: '700',
    marginLeft: 15,
    letterSpacing: 3,
    textTransform: 'uppercase',
  },
  activeIndicator: {
    position: 'absolute',
    top: 10,
    right: 10,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#00ffcc',
  },
  controlGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  featureButton: {
    width: '48%',
    backgroundColor: '#0f0f1a',
    borderRadius: 4,
    padding: 18,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(0, 255, 255, 0.12)',
    marginBottom: 10,
  },
  featureButtonActive: {
    borderColor: '#00ffff',
    backgroundColor: 'rgba(0, 255, 255, 0.05)',
  },
  alertTestButton: {
    borderColor: 'rgba(255, 0, 102, 0.3)',
    backgroundColor: 'rgba(255, 0, 102, 0.05)',
  },
  journeyShareButton: {
    borderColor: 'rgba(0, 255, 204, 0.3)',
    backgroundColor: 'rgba(0, 255, 204, 0.05)',
  },
  cyclingJourneyButton: {
    borderColor: 'rgba(255, 0, 102, 0.3)',
    backgroundColor: 'rgba(255, 0, 102, 0.05)',
  },
  featureIcon: {
    width: 40,
    height: 40,
    borderRadius: 4,
    backgroundColor: 'rgba(0, 255, 255, 0.08)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
  },
  featureButtonText: {
    color: '#e0e0e0',
    fontSize: 11,
    fontWeight: '700',
    textAlign: 'center',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  featureButtonTextActive: {
    color: '#00ffff',
  },
  featureStatus: {
    color: '#555',
    fontSize: 9,
    fontWeight: '700',
    marginTop: 4,
    letterSpacing: 2,
    textTransform: 'uppercase',
  },
  // Biometric Styles
  biometricGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginTop: 10,
  },
  biometricItem: {
    alignItems: 'center',
    width: '48%',
    backgroundColor: 'rgba(0, 255, 255, 0.04)',
    padding: 10,
    borderRadius: 4,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: 'rgba(0, 255, 255, 0.1)',
  },
  biometricValue: {
    fontSize: 22,
    fontWeight: '900',
    color: '#00ffff',
  },
  biometricLabel: {
    fontSize: 9,
    color: '#666',
    marginTop: 4,
    letterSpacing: 2,
    textTransform: 'uppercase',
  },
  // Cycling Styles
  cyclingCard: {
    backgroundColor: '#0f0f1a',
    borderColor: '#00ffcc',
    borderWidth: 1,
  },
  cyclingGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginTop: 10,
  },
  cyclingItem: {
    alignItems: 'center',
    width: '48%',
    backgroundColor: 'rgba(0, 255, 204, 0.05)',
    padding: 10,
    borderRadius: 4,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: 'rgba(0, 255, 204, 0.15)',
  },
  cyclingLabel: {
    fontSize: 9,
    color: '#666',
    marginBottom: 4,
    textAlign: 'center',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  cyclingValue: {
    fontSize: 16,
    fontWeight: '700',
    color: '#00ffcc',
    textAlign: 'center',
  },
  cyclingThreats: {
    marginTop: 15,
    padding: 10,
    backgroundColor: 'rgba(255, 0, 102, 0.08)',
    borderRadius: 4,
    borderWidth: 1,
    borderColor: 'rgba(255, 0, 102, 0.2)',
  },
  cyclingThreatsTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: '#ff0066',
    marginBottom: 8,
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  cyclingThreatItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 5,
  },
  cyclingThreatSeverity: {
    fontSize: 9,
    fontWeight: '700',
    marginRight: 8,
    minWidth: 60,
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  cyclingThreatDesc: {
    fontSize: 12,
    color: '#8a8a9a',
    flex: 1,
  },
  cyclingStatus: {
    fontSize: 11,
    color: '#555',
    textAlign: 'center',
    marginTop: 10,
    fontStyle: 'italic',
  },
  // Voice Trigger Status Styles
  statusCard: {
    backgroundColor: '#0f0f1a',
    borderRadius: 4,
    padding: 15,
    marginHorizontal: 20,
    marginBottom: 15,
    borderWidth: 1,
    borderColor: 'rgba(0, 255, 255, 0.12)',
  },
  listeningCard: {
    backgroundColor: 'rgba(0, 255, 204, 0.05)',
    borderColor: '#00ffcc',
    borderWidth: 1,
  },
  listeningIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  pulsingDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#00ffcc',
    marginLeft: 8,
    opacity: 0.8,
  },
  listeningText: {
    color: '#e0e0e0',
    fontSize: 14,
    fontWeight: '600',
    textAlign: 'center',
    marginBottom: 15,
  },
  stopListeningButton: {
    backgroundColor: 'rgba(255, 0, 102, 0.15)',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 4,
    alignSelf: 'center',
    borderWidth: 1,
    borderColor: '#ff0066',
  },
  stopListeningText: {
    color: '#ff0066',
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  // Hands-Free Mode Styles
  handsFreeCard: {
    backgroundColor: 'rgba(0, 255, 255, 0.05)',
    borderColor: '#00ffff',
    borderWidth: 1,
  },
  handsFreeIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  handsFreeTitle: {
    color: '#00ffff',
    fontSize: 14,
    fontWeight: '700',
    textAlign: 'center',
    marginBottom: 8,
    letterSpacing: 2,
    textTransform: 'uppercase',
  },
  handsFreeDescription: {
    color: '#8a8a9a',
    fontSize: 13,
    textAlign: 'center',
    marginBottom: 15,
    lineHeight: 20,
  },
  stopHandsFreeButton: {
    backgroundColor: 'rgba(255, 0, 102, 0.15)',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 4,
    alignSelf: 'center',
    borderWidth: 1,
    borderColor: '#ff0066',
  },
  stopHandsFreeText: {
    color: '#ff0066',
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  // Voice Info Only Status Styles
  voiceInfoCard: {
    backgroundColor: 'rgba(0, 255, 255, 0.05)',
    borderColor: '#00ffff',
    borderWidth: 1,
  },
  voiceInfoTitle: {
    color: '#00ffff',
    fontSize: 14,
    fontWeight: '700',
    textAlign: 'center',
    marginBottom: 8,
    letterSpacing: 2,
    textTransform: 'uppercase',
  },
  voiceInfoDescription: {
    color: '#8a8a9a',
    fontSize: 13,
    textAlign: 'center',
    marginBottom: 15,
    lineHeight: 20,
  },
  stopVoiceInfoButton: {
    backgroundColor: 'rgba(255, 0, 102, 0.15)',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 4,
    alignSelf: 'center',
    borderWidth: 1,
    borderColor: '#ff0066',
  },
  stopVoiceInfoText: {
    color: '#ff0066',
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  // Alert Status Card Styles
  alertStatusCard: {
    backgroundColor: 'rgba(255, 0, 102, 0.1)',
    borderColor: '#ff0066',
    borderWidth: 2,
  },
  alertHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 15,
  },
  alertStatusTitle: {
    color: '#ff0066',
    fontSize: 14,
    fontWeight: '700',
    marginLeft: 10,
    marginRight: 10,
    letterSpacing: 2,
    textTransform: 'uppercase',
  },
  alertDetails: {
    marginBottom: 15,
  },
  alertDetailItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    padding: 10,
    borderRadius: 4,
    borderLeftWidth: 2,
    borderLeftColor: '#ff0066',
  },
  alertDetailText: {
    color: '#e0e0e0',
    fontSize: 12,
    marginLeft: 10,
    flex: 1,
  },
  alertContactsList: {
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    padding: 12,
    borderRadius: 4,
    marginBottom: 15,
    borderWidth: 1,
    borderColor: 'rgba(0, 255, 204, 0.2)',
  },
  alertContactsTitle: {
    color: '#00ffff',
    fontSize: 11,
    fontWeight: '700',
    marginBottom: 8,
    letterSpacing: 2,
    textTransform: 'uppercase',
  },
  alertContact: {
    color: '#00ffcc',
    fontSize: 13,
    marginBottom: 4,
  },
  deactivateAlertButton: {
    backgroundColor: 'rgba(255, 0, 102, 0.2)',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 4,
    alignSelf: 'center',
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#ff0066',
  },
  deactivateAlertText: {
    color: '#ff0066',
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  alertNote: {
    color: '#555',
    fontSize: 11,
    textAlign: 'center',
    fontStyle: 'italic',
    marginTop: 5,
  },
  // Language Picker Styles
  languageButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: 'rgba(0, 255, 255, 0.08)',
    borderRadius: 2,
    borderWidth: 1,
    borderColor: 'rgba(0, 255, 255, 0.3)',
  },
  languageCode: {
    color: '#00ffff',
    fontSize: 10,
    fontWeight: '700',
    marginLeft: 4,
    letterSpacing: 2,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.9)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  languageModal: {
    backgroundColor: '#0d0d15',
    borderRadius: 4,
    width: '85%',
    maxHeight: '70%',
    padding: 20,
    borderWidth: 1,
    borderColor: 'rgba(0, 255, 255, 0.2)',
  },
  languageModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
    paddingBottom: 15,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0, 255, 255, 0.1)',
  },
  languageModalTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#00ffff',
    flex: 1,
    letterSpacing: 2,
    textTransform: 'uppercase',
  },
  languageList: {
    maxHeight: 400,
  },
  languageOption: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 15,
    marginBottom: 10,
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    borderRadius: 4,
    borderWidth: 1,
    borderColor: 'transparent',
  },
  languageOptionActive: {
    backgroundColor: 'rgba(0, 255, 255, 0.08)',
    borderColor: '#00ffff',
  },
  languageFlag: {
    fontSize: 32,
    marginRight: 15,
  },
  languageName: {
    fontSize: 14,
    color: '#e0e0e0',
    flex: 1,
  },
  languageNameActive: {
    color: '#00ffff',
    fontWeight: '700',
  },
  // Radar Active Indicator Styles
  radarActiveIndicator: {
    marginTop: 10,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 8,
  },
  radarContainer: {
    width: 50,
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
  },
  radarRingAnimated: {
    position: 'absolute',
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: '#00ffff',
  },
  radarCenterDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#00ffff',
  },
  radarPulse: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#00ffff',
    opacity: 0.8,
    marginBottom: 4,
  },
  radarActiveText: {
    color: '#00ffff',
    fontSize: 9,
    fontWeight: '700',
    textAlign: 'center',
    letterSpacing: 2,
    textTransform: 'uppercase',
    marginTop: 4,
  },
  // Privacy Policy Styles
  privacyHeading: {
    fontSize: 20,
    fontWeight: '900',
    color: '#00ffff',
    marginBottom: 8,
    letterSpacing: 2,
    textTransform: 'uppercase',
  },
  privacyDate: {
    fontSize: 12,
    color: '#555',
    marginBottom: 25,
    letterSpacing: 1,
  },
  privacySectionTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#ff0066',
    marginTop: 20,
    marginBottom: 8,
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  privacyText: {
    fontSize: 13,
    color: '#8a8a9a',
    lineHeight: 22,
    marginBottom: 5,
  },
  // Footer Styles
  footer: {
    alignItems: 'center',
    paddingVertical: 30,
    paddingHorizontal: 20,
    marginTop: 20,
  },
  footerDivider: {
    width: '60%',
    height: 1,
    backgroundColor: 'rgba(0, 255, 255, 0.1)',
    marginBottom: 15,
  },
  footerDisclaimerBold: {
    color: '#ff0066',
    fontSize: 10,
    fontWeight: '700',
    textAlign: 'center',
    letterSpacing: 1,
    textTransform: 'uppercase',
    marginBottom: 12,
  },
  footerLink: {
    color: '#00ffff',
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 2,
    textTransform: 'uppercase',
    marginBottom: 10,
  },
  footerVersion: {
    color: '#333',
    fontSize: 10,
    letterSpacing: 1,
    marginBottom: 6,
  },
  footerDisclaimer: {
    color: '#333',
    fontSize: 9,
    textAlign: 'center',
    letterSpacing: 0.5,
    lineHeight: 14,
  },
});
